= Nuclear Waste Invaders
:revdate: 2020-12-05
:linkattrs:
:toc:
:toc-title:

// This file is part of Nuclear Waste Invaders
// http://programandala.net/en.program.nuclear_waste_invaders.html

// This document is written in Asciidoctor format
// http://asciidoctor.org

// You may do whatever you want with this work, so long as you retain
// the copyright/authorship/acknowledgment/credit notice(s) and this
// license in all redistributed copies and derived works.  There is no
// warranty.

== English

// tag::en[]

=== Project

_Nuclear Waste Invaders_ is a ZX Spectrum 128 remake, under
development, of Jupiter ACE computer's
http://www.zonadepruebas.com/viewtopic.php?t=4231[Nuclear Invaders,
role="external"] (Dancresp, 2013).

It is written in
http://standard-forth.org[Forth,role="external"] with
http://programandala.net/en.program.solo_forth.html[Solo Forth]
(http://github.com/programandala-net/solo-forth[Solo Forth in
GitHub,role="external"]).

Web page:
http://programandala.net/en.program.nuclear_waste_invaders.html.

:note-caption: Note
NOTE: On 2020-12-05 the Git repository was converted to
http://fossil-scm.rog[Fossil]. GitHub is used only as a copy.

=== How to compile and run

If you cannot wait until the first public version is resealed, you can
build the program yourself:

. Make sure the required programs, listed in the header of the
  <Makefile> file, are installed on your system.
. Type `make` in the project directory to build the
  <disk_2_nuclear_waste_invaders.mgt> disk image and the
  <graphics.tap> tape image.
. Start a ZX Spectrum 128 emulator with the Plus D interface.
. Enter 128 BASIC.
. Insert the Solo Forth's <disk_0_boot.mgt> disk image into disk drive
  1 of your emulator.
. Type the BASIC command `run` to load G+DOS and Solo Forth from disk drive 1.
. Insert the <disk_2_nuclear_waste_invaders.mgt> disk image into disk
  drive 1 of your emulator.
. Open the <graphics_and_font.tap> tape image as the input tape of
  your emulator.
. Type Forth command `1 load` to load block 1 from the current drive. This will
  start the compilation. Messages will be shown during the process.
. Set your emulator to its maximum speed and wait. When the
  compilation is finished, the screen is cleared and a message is
  displayed.
. Set your emulator to the normal speed (100%).
. In order to save the compiled game, create a SZX snapshot with your
  emulator.
. Type `run` in Forth to start the game.

// end::en[]

== Español

// tag::es[]

=== Proyecto

_Nuclear Waste Invaders_ (Invasores de residuos nucleares) es una
reinterpretación en desarrollo para ZX Spectrum 128, del
http://www.zonadepruebas.com/viewtopic.php?t=4231[Nuclear Invaders,
role="external"] (Dancresp, 2013) de la computadora Jupiter Ace.

Está escrito en
http://standard-forth.org[Forth,role="external"] con
http://programandala.net/en.program.solo_forth.html[Solo Forth]
(http://github.com/programandala-net/solo-forth[Solo Forth en
GitHub,role="external"]).

Página en la red:
http://programandala.net/es.programa.nuclear_waste_invaders.html.

:note-caption: Nota
NOTE: En 2020-12-05 el repositorio Git fue convertido a
http://fossil-scm.org[Fossil]. GitHub se usa solo
como una copia.

=== Cómo compilar y arrancar

Si no puedes esperar a la salida de la primera versión pública, puedes
construir el programa tú mismo:

. Asegúrate de que los programas necesarios, que están listados en la
  cabecera del fichero <Makefile>, están instalados en tu sistema.
. Da la orden `make` en el directorio del proyecto para construir la
  imagen de disquete <disk_2_nuclear_waste_invaders.mgt> y la imagen
  de cinta de casete <graphics.tap>.
. Arranca un emulador de ZX Spectrum 128 con la interfaz Plus D.
. Entra en 128 BASIC.
. Inserta la imagen de disquete <disk_0_boot.mgt> de Solo Forth en la
  disquetera 1 de tu emulador.
. Da el comando de BASIC `run` para cargar G+DOS y Solo Forth desde la
  disquetera 1.
. Inserta la imagen de disquete <disk_2_nuclear_waste_invaders.mgt> en
  la disquetera 1 de tu emulador.
. Abre la imagen de cinta de casete <graphics_and_font.tap> como cinta
  de entrada de tu emulador.
. Escribe el comando de Forth `1 load` para cargar el bloque 1 de la
  disquetera actual. Esto iniciará la compilación. Durante el proceso
  se mostrarán mensajes en la pantalla.
. Pon la velocidad de tu emulador al máximo y espera. Cuando la
  compilación haya terminado, se borrará la pantalla y se mostrará un
  mensaje.
. Pon tu emulador a la velocidad normal (100%).
. Para guardar el juego compilado, crea una imagen del sistema en
  formato SZX usando tu emulador.
. Escribe `run` en Forth para empezar el juego.

// end::es[]

== Esperanto

// tag::eo[]

=== Projekto

Se vi ne povas atendi li aperon de la unua publika versio, vi mem
povas konstrui li programon:

_Nuclear Waste Invaders_ (Atomrubaĵaj Invadantoj) esta programata
reinterpreto, por la komputilo ZX Spectrum 128, el
http://www.zonadepruebas.com/viewtopic.php?t=4231[Nuclear Invaders,
role="external"] (Dancresp, 2013) de la komputilo Jupiter ACE.

Ĝi estas verkata en http://standard-forth.org[Forth,role="external"]
per http://programandala.net/en.program.solo_forth.html[Solo Forth]
(http://github.com/programandala-net/solo-forth[Solo Forth en
GitHub,role="external"]).

Retpaĝo:
http://programandala.net/eo.programo.nuclear_waste_invaders.html.

:note-caption: Noto
NOTE: Je 2020-12-05 la Git-deponejo estis konvertita al
http://fossil-scm.org[Fossil]. GitHub estas uzata nur kiel kopio.

=== Kiel kompili kaj funkciigi

. Certiĝu ke la necesaj programoj, listigitaj supre de la dosiero
  <Makefile>, estas instalitaj en via sistemo.
. Tajpu `make` en la dosierujo de la projekto por krei la diskedeskan
  dosieron <disk_2_nuclear_waste_invaders.mgt> kaj la kasedeskan
  dosieron <graphics.tap>.
. Enmetu la diskedeskan dosieron <disk_0_boot.mgt> de Solo Forth en la
  diskedujon 1 de via emulilo.
. Skribu la BASIC-ordonon `run` por funkciigi G+DOS kaj Solo Forth el
  la diskedujo 1.
. Enmetu la diskedeskan dosieron <disk_2_nuclear_waste_invaders.mgt>
  en la diskedujon 1 de via emulilo.
. Malfermu la kasedeskan dosieron <graphics_and_font.tap> kiel
  enir-kasedon de via emulilo.
. Skribu ordonon de Forth `1 load` por preni blokon 1 el la nuna
  diskedujo. Ĉi tio komencos la kompiladon, dum kiu mesaĝoj estos
  montrataj sur la ekrano.
. Elektu la plej grandan rapidon de via emulilo kaj atendu. Kiam la
  kompilado finiĝos, la ekrano estos forviŝita kaj mesaĝo estos
  printita.
. Elektu normalan (100%) rapidon en via emulilo.
. Por konservi la kompilitan ludon, kreu kopion de la tuta sistemo en
  SZX-formata dosiero, uzante vian emulilon.
. En Fortho tajpu `run` por komenci la ludon.

// end::eo[]

== Interlingue

// tag::ie[]

=== Projecte

_Nuclear Waste Invaders_ (Invasores de jetallia nucleari) es un
reinterpretation, developat por ZX Spectrum 128, del
http://www.zonadepruebas.com/viewtopic.php?t=4231[Nuclear Invaders,
role="external"] (Dancresp, 2013) del computator Jupiter ACE.

It es scrit in
http://standard-forth.org[Forth,role="external"] con
http://programandala.net/en.program.solo_forth.html[Solo Forth]
(http://github.com/programandala-net/solo-forth[Solo Forth in
GitHub,role="external"]).

Págine web:
http://programandala.net/ie.programa.nuclear_waste_invaders.html.

:note-caption: Note
NOTE: In 2020-12-05 li depositoria de Git esset convertet a
http://fossil-scm.org[Fossil]. GitHub es usat solmen quam un copie.

=== Qualmen compilar e initiar

Si vu ne posse atender li aparition del prim version public, vu self
posse constructer li programma:

. Controla que li necessi programmas, quel es listat in li supra del
  document <Makefile>, es instalat in vor computator.
. Comanda `make` in li documentiere del projecte por constructer li
  disco-replica <disk_2_nuclear_waste_invaders.mgt> e li bande-replica
  <graphics.tap>.
. Initia un emulator de ZX Spectrum 128 con li interfacie Plus D.
. Intra in 128 BASIC.
. Inserte li disco-replica <disk_0_boot.mgt> de Solo Forth in li
  disciere 1 de vor emulator.
. In BASIC comanda `run` por cargar G+DOS e Solo Forth del disciere 1.
. Inserte li disco-replica <disk_2_nuclear_waste_invaders.mgt> in li
  disciere 1 de vor emulator.
. Aperte li bande-replica <graphics_and_font.tap> quam bendo de
  intrada de vor emulator.
. In Forth comanda `1 load` por cargar li bloc 1 del disciere activ.
  To va comensar li compilation. Durante li operation, divers missages
  va aparerir sur li ecran.
. Etablisse li maxim rapiditá de vor emulador e atende. Quande li
  compilation es finit, li ecran va nettar se e un missage va aparir.
. Etablisse un rapiditá normal (100%) in vor emulator.
. Por conservar li lude compilat, fa un replica del sistema con
  formate SZX usante vor emulator.
. In Forth comanda `run` por comensar li lude.

// end::ie[]

