= Nuclear Waste Invaders To-Do
:author: Marcos Cruz (programandala.net)
:revdate: 2018-01-22

Older first:

== 2016-08-01

Several players, say 1..4. Simply, save their controls number and score in a
table.

== 2016-10-16, 2018-01-07

- Effect: the invaders eat the containers.
- Keep moving the projectiles and the invaders after the invasion,
  during the future final effect.

== 2016-10-22

Detect if a wall is already broken, and change the graphic
accordingly.

== 2016-12-02

Fix: sometimes the projectile erases half of the invader.

== 2016-12-04, 2017-05-17

Use stamina to calculate the damages to the mothership.

== 2017-02-26, 2017-05-14, 2018-01-11

- Get more ammo below the building.

== 2017-02-28, 2017-12-19

- Make the tank delay through the building.
- Make a hit invader randomly move up to the next layer, if it's free.

== 2017-01-13

Improve the visibility of the projectile right above the tank.

== 2017-03-01, 2017-12-19

- Add a data field to hold the identifier of the current status
  (attacking, docked, breaking the wall, retreating...). This will be
  simpler to use and more versatile.
- Change the graphics of the invaders that are delayed at the wall.

== 2017-03-01

Add some inertia to the tank.

== 2017-03-17

Create a sprite frames table to point to UDG frames, in order to
remove duplicated frames from the UDG set.

== 2017-04-18

- Write Z80 code to print 2x1 sprites faster.

== 2017-05-12

- Don't repair the building automatically. Use the tank.

== 2017-05-16

Improve `battle-bonus`: Make the breach penalty depend on the altitude
of the breachs.

== 2017-05-20, 2018-01-06

Replace the UDG codes with the UDG addresses and write a new faster
version of `.2x1-udg-sprite`, in Z80, without the conversion from code
to address.

== 2017-12-06

- Make `defeat-tune` an alarm and use it when an alien touches the
  wall.

== 2017-12-18

- Improve scoring: reduce the score with each movement and projectile.
- Move the localization tools to Solo Forth.

== 2017-12-19

- Make the mothership cure invaders.

== 2017-12-22

- Make launching the beam a bit random.
- Make the mothership's movement clever: stay longer above the
  building, and go probably to the side where invaders need help or
  the opposite side of the tank.
- Add stamina control to the mothership, deactivate the beam when the
  stamina is not the highest, and place the mothership above the
  building for repairing.
- Change the mothership's range randomly during the game.

== 2017-12-27

- Remove `invader#` and use only the corresponding data addresses?

== 2018-01-03

- Finish regularizing the names of the sprites. The static graphics
  have no suffix.

== 2018-01-07

- Simplifly the way `hit-something?` and `impacted?` are used.
- Improve `mortal?` using the y coordinate in the calculation.
- Remove `turn-back` and use its factor `change-direction` instead,
  because the sprite does not need to be set when the direction is
  changed.
- Replace the run-time calculation done in `hit-wall?` and
  `prepare-wall` with a table of constants calculated at compile-time.
- Use `,udg-block` to create the sprites and use their address instead
  of their character codes.

== 2018-01-08

- Improve the graphics of the explosion.
- Make `mothership-bonus` faster with `flip`.

== 2018-01-10

- Make sound of mothership explosion longer. Manage it in
  `exploding-mothership-action`.
- Idea: Make `manage-mothership` deferred, replacing
  `do-mothership-action`, and duplicate its current functions
  (checking, timing and scheduling) into every action.  This will be a
  bit faster, saving one nesting level.

== 2018-01-17

- Generalize the detection of the projectile in the flying invader
  actions: detect also the wall and the containers.

- Limit the number of bullets and missiles.

== 2018-01-21

- Remove `damage-transmission` and friends.
- Improve the logic of `(invader-impacted`: First `wounded`, then
  `mortal?`. But make the wound a bit random: otherwise the green
  invaders will never explode.
- Convert `invader-proper-attr` to `stamina>attr` to reuse it for the
  mothership.

- 64-cpl status bar:

....
<-------------------------------------------------------------->
Bullets:00 Missiles:00                  Score:00000 Record:00000
B:00 M:00 Score:0000 Record:0000
B:00 M:00 Puntos:0000 Récor:0000
B:00 M:00 Poentoj:0000 Rikordo:0000
B:00 M:00 Score:0000/0000
B:00 M:00 Puntos:0000 Récor:0000
B:00 M:00 Poentoj:0000 Rikordo:0000
<-------------------------------------------------------------->
....

== 2018-01-22

- 32-cpl status bar with icons (X) and full labels:

....
<------------------------------>
X00 X00          Score:0000/0000
X00 X00         Puntos:0000/0000
X00 X00        Poentoj:0000/0000
X00 X00   Score:0000 Record:0000
X00 X00   Puntos:0000 Récor:0000
X00 X00 Poentoj:0000 Rikordo:0000 [!]
<------------------------------>
....


- Make missiles affected by wind and display a weather vane in the
  status bar.
