= Nuclear Invaders To-Do
:author: Marcos Cruz (programandala.net)
:revdate: 2016-11-17

2016-08-01:

Several players, say 1..4. Simply, save their controls number and score in a
table.

2016-10-12:

Use pixels instead of characters as projectiles.

2016-10-15:

Show an icon of the free projectiles: A graphic with 0..3 bars, or
0..3 graphics.

2016-10-16:

Effect: the invaders eat the containers.

Idea: Don't repair the building when using a new life...

Keep moving the projectiles and the invaders after the invasion,
during the future final effect.

Change the color of explosions.

Animate the explosions with several frames.

2016-10-18:

Make the speed of the invaders regular, no matter the number of them.

2016-10-22:

Detect if a wall is already broken, and change the graphic
accordingly.

2016-11-17:

When an invader is shoot, make it return to the border of the arena,
and then start over.

2016-11-27:

Count the times every invader is hit and change its color accordingly.
Make the explosion random calculation depend on the count.
