= Nuclear Waste Invaders To-Do
:author: Marcos Cruz (programandala.net)
:revdate: 2017-12-31

Older first:

== 2016-08-01

Several players, say 1..4. Simply, save their controls number and score in a
table.

== 2016-10-12

Use pixels instead of characters as projectiles.

== 2016-10-15

Show a graphic of the ammo left.

== 2016-10-16

Effect: the invaders eat the containers.

Keep moving the projectiles and the invaders after the invasion,
during the future final effect.

Change the color of explosions.

Animate the explosions with several frames.

== 2016-10-22

Detect if a wall is already broken, and change the graphic
accordingly.

== 2016-12-02

Fix: sometimes the projectile erases half of the invader.

== 2016-12-04, 2017-05-17

Use stamina to calculate the damages to the mothership.

== 2017-02-26, 2017-05-14

Max ammo, with a method or place to get more.

Get more ammo by firing below the building.

== 2017-02-28, 2017-12-19

- Make the tank delay through the building.
- Make a hit invader randomly move up to the next layer, if it's free.

== 2017-01-13

Improve the visibility of the projectile right above the tank.

== 2017-03-01, 2017-12-19

- Add a data field to hold the identifier of the current status
  (attacking, docked, breaking the wall, retreating...). This will be
  simpler to use and more versatile.
- Change the graphics of the invaders that are delayed at the wall.

== 2017-03-01

Add some inertia to the tank.

== 2017-03-17

Create a sprite frames table to point to UDG frames, in order to
remove duplicated frames from the UDG set.

== 2017-04-18

- Write Z80 code to print 2x1 sprites faster.
- Simplify the status bar, remove the texts, display only "0000/0000".

== 2017-05-12

- Don't repair the building automatically. Use the tank.

== 2017-05-16

Improve `battle-bonus`: Make the breach penalty depend on the altitude
of the breachs.

== 2017-05-20

Replace the UDG codes with the UDG addresses and write a new faster
version of `.2x1sprite`, in Z80, without the conversion from code to
address.

== 2017-05-21

Improve the explosion of the mothership. Now it's almost unobservable.

Possible method to make the explosion longer without halting the game
loop:

- Change its graphic to a sequence of explosion frames.
- Change its x coordinate increment to 0.
- Update its detection accordingly.
- Change its y coordinate to zero only when the explosion has
  finished.

== 2017-12-06

- Make `defeat-tune` an alarm and use it when an alien touches the
  wall.

== 2017-12-18

- Improve scoring: reduce the score with each movement and projectile.
- Move the localization tools to Solo Forth.

== 2017-12-19

- Make the mothership cure invaders.

== 2017-12-20

- Improve the top and the bottom of the beam.

== 2017-12-22

- Make launching the beam a bit random.
- Make the mothership's movement clever: stay longer above the
  building, and go probably to the side where invaders need help or
  the opposite side of the tank.
- Add stamina control to the mothership, deactivate the beam when the
  stamina is not the highest, and place the mothership above the
  building for repairing.
- Change the mothership's range randomly during the game.

== 2017-12-27

- Remove `invader#` and use only the corresponding data addresses?

== 2017-12-31

- Improve `attack-report` to display the texts immediately.
